### ISSUE TITLE
Database Analysis of Alternatives

### ISSUE THREAD

**Issue by LanceGundersen** [stanglab/tbinge#1]
Database Choice: TBD

- [ ] Decide on SQLite vs. Flat File
- [ ] Test Implementation
- [ ] Decision Reached

**Comment by flansah** [comment]
I have looked at the SQlite and I think it will be safe for us to use it instead of the flat file base on the following:
- SQlite will accommodate structured-bulky data.
-Deleting records will be much easier.
- Creating and updating records are much easier with SQlite.

**Comment by LanceGundersen** [comment]
I am not sure integrating an entire DB is necessary for the initial minimum viable product (MVP) and the node.js _fs_ (file system) module should suffice adequately in my opinion. 
[Read a bit here about different strategies](https://medium.com/cameron-nokes/how-to-store-user-data-in-electron-3ba6bf66bc1e)
[Node.js FS Tutorial](https://stackabuse.com/reading-and-writing-json-files-with-node-js/)

Food for thought.

**Comment by LanceGundersen** [comment]
@flansah have a look at this: https://medium.com/cameron-nokes/how-to-store-user-data-in-electron-3ba6bf66bc1e I believe you may have to do some test cases to see which platform it's on and then choose the file save location for the tbingedata.json file.
