### ISSUE TITLE
Integrate TMDB API call on initial movie search

### ISSUE THREAD

**Issue by LanceGundersen** [stanglab/tbinge#21]
In the movies.vue the method filterTmdbList needs to be removed and a method call to the TMDB API put in place. I have implemented all GUI template items.

The desired actions are:

1. Queries TMDB based on searchInputTmdb input string
2. Displays results in the drawer

**Comment by Drbaltar** [comment]
Issue is resolved with the pull-request from tmdb-search-integration.
