### ISSUE TITLE
Integrate detailed TMDB API call on movie search

### ISSUE THREAD

**Issue by LanceGundersen** [stanglab/tbinge#22]
In the movies.vue the method viewTmdbDetail needs to call the TMDB API. I have implemented all GUI template items.

The desired actions are:

1. Queries TMDB based on given id
2. Displays results in the DetailDialog.vue

**Comment by Drbaltar** [comment]
nedb-kyle branch corrected this issue and now the trailer information is displayed if the user clicks "Details" for a returned movie/TV show
