### ISSUE TITLE
Main Menu not appearing

### ISSUE THREAD

**Issue by Drbaltar** [stanglab/tbinge#28]
![image](https://user-images.githubusercontent.com/26285272/53302536-49359980-381c-11e9-8e23-71fa306fa5e8.png)

The Main Menu only appears when the developer tools are up. Otherwise, it shows up like the screenshot above.

**Comment by LanceGundersen** [comment]
I can confirm this is a bug. This is leftover code from the template and needs to be removed.

**Comment by LanceGundersen** [comment]
I noticed even with this fix the logo "jitters" when the devtools is closed. I don't think this is an issue though as it only affects the dev mode, not production.
