### ISSUE TITLE
Can add Movie or TV Show that is already in the List

### ISSUE THREAD

**Issue by Drbaltar** [stanglab/tbinge#31]
When you are trying to add a new movie or TV show, the system will allow the user to add multiple instances of the same movie or show.

**Comment by LanceGundersen** [comment]
This is a good catch. I can handle this on the front end before the call to the tmdb API by checking the local  data set first.

**Comment by LanceGundersen** [comment]
1. Call API and store results within this method (tmdbSearchResults)
2. Check stored results against localMovies dataset
3. Iterate through the tmdbSearchResults ids
4. If an id equals one in the localMovies then push to that tmdbSearchResults.id an inLibrary boolean.
5. return tmdbSearchResults
6. Template check if in library and remove the "Add to Library" button and replace with "In Library"

**Comment by Drbaltar** [comment]
nedb-kyle branch corrected this issue and now an alert is displayed to the user if they try to add an entry that is already stored in their media list.
