### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by LanceGundersen** [stanglab/tbinge#5]
Front end layout and designs.

- [x] Search View
- [x] Movies List View
- [x] TV List View
- [x] Movie/TV Details View

![cmsc495 project-1](https://user-images.githubusercontent.com/8315447/51793742-561a8b00-2193-11e9-858a-fc7e75f595ab.jpg)

**Comment by flansah** [comment]
Design features looks good to me, but we can modify "search view" to "new search".

**Comment by LanceGundersen** [comment]
@flansah I am not sure what you are referring to.

**Comment by flansah** [comment]
@LanceGundersen  I was referring to "Front end layout and designs". Disregard, because the layouts are already captured in the project designed shown above. It will not make sense to rename it.

**Comment by LanceGundersen** [comment]
https://xd.adobe.com/view/7dab5e80-2a20-46b4-5749-5cc3ccb49e6d-0b9a/

**Comment by LanceGundersen** [comment]
https://xd.adobe.com/view/7dab5e80-2a20-46b4-5749-5cc3ccb49e6d-0b9a/screen/fb08e8eb-b460-4860-a78d-66803319674d/TV/
